config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Root path
  root 'events#index'

  # User Authentication Routes
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  # Events Resource
  resources :events do
    resources :registrations, only: [:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Buster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all" %>
  </head>

  <body>
    <nav class="nav-bar">
      <% if logged_in? %>
        <span>Welcome, <%= current_user.username %>!</span>
        <!-- logout using POST becuase delete was not working -->
        <%= button_to 'Logout', logout_path, method: :post, class: "button" %>
      <% else %>
        <%= link_to 'Login', login_path, class: "nav-link" %> |
        <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
      <% end %>
    </nav>
      
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>